### ISSUE TITLE
bake update always says the same thing

### ISSUE THREAD

**Issue by ghitchens** [ghitchens/bake#12]
gmb:blinky garth$ bake update
Downloading update
Unpacking Update
Update Complete
gmb:blinky garth$ 

That's true regardless of whether or not it really downloads or does an update.   In this case it didn't.  Or maybe it always does, which seems wrong.   Either way.

**Comment by mobileoverlord** [comment]
Currently it updates to the latest and does not check if it is a version greater than the current one. I'll change this to first check for update.

**Comment by mobileoverlord** [comment]
fixed in master bakeware/bake@5a99193df28878a567424e5d12c78f534e0b6951
