### ISSUE TITLE
recipe.exs is missing for rpi 0.1.0

### ISSUE THREAD

**Issue by alfert** [ghitchens/bake#16]
Hi, 

at first: I am impressed! I tried bake for my Rasperry Pi B together with the nerve-examples (Blinky in particular). So I added the target `rpi`to my `Bakefile`: 

``` elixir
use Bake.Config

platform :nerves
default_target :rpi

target :rpi,
  recipe: {"nerves/rpi", "~> 0.1"}

target :rpi2,
  recipe: {"nerves/rpi2", "~> 0.1"}

target :bbb,
  recipe: {"nerves/bbb", "~> 0.1"}
```

Running `bake system get`works, but `bake toolchain get` failed with: 

```
bake toolchain get
=> Get toolchain for target rpi
** (MatchError) no match of right hand side value: {:error, %Code.LoadError{file: "/Users/kal/.nerves/systems/nerves/rpi-0.1.0/recipe.exs", message: "could not load/Users/kal/.nerves/systems/nerves/rpi-0.1.0/recipe.exs"}}
    (bake) lib/bake/cli/toolchain.ex:63: anonymous fn/4 in Bake.Cli.Toolchain.get/1
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

Setting the target to `rpi2` works like a charm. 

Regards,
Klaus.

**Comment by mobileoverlord** [comment]
HI Klaus,
Sorry for the problem with the rpi system. I have fixed it in production. To use the system and toolchain, you will need to clean your system and get it again. Please execute the following from within your project. Assuming that your target is `rpi`

`bake system clean --target rpi`
`bake system get --target rpi`
`bake toolchain get --target rpi`

Thanks!

**Comment by alfert** [comment]
Thanks, works now like a charm!
