### ISSUE TITLE
linux_install_deps: fwup v0.5.0 or later required

### ISSUE THREAD

**Issue by ramstein74** [ghitchens/bake#25]
Hello for a newbie the docs are too much simple.Please detail a litle more...
I installed bake via
ruby -e "$(curl -fsSL https://bakeware.herokuapp.com/bake/install)"
and i get the error 
![image](https://cloud.githubusercontent.com/assets/1210858/13600640/08cda9a0-e522-11e5-9589-37b7861b7246.png)

i have an ubuntu 14.04 server

**Comment by mobileoverlord** [comment]
Yup, sorry we are working on improving the documentation and installation procedure. For Linux you are going to have to install a selection of additional deps for bake. One of which is fwup. @fhunleth has recently started packing this into rpm's and deb's for easier installation. You can find them on the latest release https://github.com/fhunleth/fwup/releases/tag/v0.6.1 let us know if you encounter other installation issues
