### ISSUE TITLE
Add version locking for platforms, systems, and toolchains

### ISSUE THREAD

**Issue by mobileoverlord** [ghitchens/bake#4]
We need to ensure that based off the Bakefile users are going to be able to produce consistent firmware after checking out of SCM.

**Comment by mobileoverlord** [comment]
Once toolchain and system versioning get implemented there is potential for a lot of large abandoned trash to accumulate in the shared systems / tool chains directories. For example, if you're on 0.4.0 of a system and in a project you update to 0.4.1, there are now both versions on disk. With the weight of systems and tool chains, this could add up especially for ultra portable machines.

**Comment by mobileoverlord** [comment]
I was first considering approaching this by performing multiple steps.
1. Limit the number of versions that the same system would cache on disk and save this in a machine configuration in `BAKE_HOME`. This would automatically prune the oldest version when a new version is fetched with `bake system get`.
2. create commands for performing housekeeping on downloaded systems and toolchains. Currently there are commands available to clean an individual system or toolchain for a target
`bake system clean [--target]`

I would suggest the addition of the following commands

Display a list of systems installed for the recipe listed in the Bakefile for the target bbb or pass --recipe and call direct

```
bake system list [--target bbb | --recipe nerves/bbb]

Installed system versions for recipe nerves/bbb
* 0.4.0 (active)
* 0.3.6
* 0.3.5
```

Clean a version of a system. pass `--all` instead of `--version` to clean all versions of the system

```
brew system clean --recipe nerves/bbb --version 0.4.0 [-all]
==> Cleaning system nerves/bbb version 0.4.0
```

The same commands can be used for toolchain management

**Comment by ghost** [comment]
How is "active" figured out or is it the newest version? Regarding `--all`, I think that I'd more commonly be cleaning up everything besides the "active" version rather than every version?

**Comment by mobileoverlord** [comment]
I guess active could only be determined if you ran the command against a bakefile target. like
`bake system list --target bbb` It would be able to determine what is the active system version being used in accordance to the `bakefile.lock` in the project

This would not however be able to tell you which versions other projects around your machine may be requiring.

**Comment by ghost** [comment]
In some sense, deleting a system or toolchain that you're using isn't the worst thing since you just have to pay the download penalty and don't lose anything. At the end of a project or even at various points, I usually need to archive all external tarballs that go into the project so that it can be rebuilt without Internet access. I realize that's not this bug, but it feels related. Being able to show that if `bakeware.io` goes down that all is not lost is a nice to have. (Maybe that means that I can manually populate the toolchain and system cache if I'm desparate?)

**Comment by mobileoverlord** [comment]
I am going to continue the discussion of managing dangling systems and toolchains in another issue. As for locking this is added in master
